### ISSUE TITLE
[2.8.3] Activate icon flickers on screen

### ISSUE THREAD

**Issue by zhuabaobao123** [Ryan-rsm-McKenzie/QuickLootRE#106]
with the new update sometimes the "E" [activate] icon flickers on the screen.

**Comment by zhuabaobao123** [comment]
【AIM FIX Lite】 【SmoothCam】【 Less Intrusive HUD 】【Customizable UI Replacer SE】 【ihudImmersive HUD】 This is me, all I use

**Comment by Ryan-rsm-McKenzie** [comment]
This happens in vanilla skyrim

**Comment by Ryan-rsm-McKenzie** [comment]
This is a different bug related to tracking life state changes
