### ISSUE TITLE
Controller D-pad not working for selection, but mouse scroll is?

### ISSUE THREAD

**Issue by mayo153** [Ryan-rsm-McKenzie/QuickLootRE#107]
Hello! Love the mod and have used an older version a long time back without any problems. Noticed a weird incompatibility with playing on a controller when I used the latest version (installed 2.8.2 and then even when updated to 2.8.4) where I can't use the controller d-pad up and down buttons to select what I want to loot. The menu and everything displays fine, I just can't move what i'm selecting without using the mouse to scroll up and down which is a bother when playing on a controller. Is there a workaround for this? i.e. can there be an option to bind the scroll up and down buttons to the controller d-pad for people that play with controllers?

Thanks for all your great work! Absolutely essential mod for me, I really don't want to play without it.

**Comment by Ryan-rsm-McKenzie** [comment]
You have a mod conflict

**Comment by mayo153** [comment]
What kind of mods could conflict with the controls for this? I don't
believe I have anything that would interfere but i'll go through the list.
I also noticed that the up/down buttons on my keyboard as well as the left
stick/right stick buttons on my gamepad work so controls can be recognized
by my controller but it's mapped to the wrong place.

**Comment by mayo153** [comment]
Solved it!!! It was an issue with my DS4Windows. Please disregard and keep up the great work.
