### ISSUE TITLE
Containers owned by friends not recognizing items as illegal to take

### ISSUE THREAD

**Issue by zauberparacelsus** [Ryan-rsm-McKenzie/QuickLootRE#109]
If a container is owned by a friend of the player, then *all* items displayed by quickloot will show as "legal" items, even if they would show as illegal in the full inventory interface.

Additionally, if an otherwise-illegal item is showing as "legal" in the quickloot interface, then not only are you are free to take it without incurring a bounty for stealing, but the item will not be flagged as stolen in your inventory.

**Comment by Ryan-rsm-McKenzie** [comment]
Do you have an easy way to reproduce this?

**Comment by NimRo97** [comment]
After you bring back the golden claw to Riverwood trader and finish the quest, you can observe this on containers in his shop (for instance the one on the right when you enter the store).

**Comment by Ryan-rsm-McKenzie** [comment]
I can't replicate this.

**Comment by Velgus** [comment]
You're likely mistaking a mod bug for the intentional [disposition feature](https://en.uesp.net/wiki/Skyrim:Disposition) in the vanilla game. When your disposition raises with NPCs (eg. after turning in a quest for them, such as the Golden Claw), it will allow you to take items they own up to a certain value, based on their current dispostion level. If the values are higher than mentioned in that article, perhaps you have a mod making disposition more effective.

**Comment by TheDanielKemp** [comment]
This is not the disposition feature. This is a bug that I am able to replicate as well. And there's actually more to it than zauber originally described. As well as quickloot showing all items in a friendly container as legal to take, even if one or more items in the container are actually illegal, if a friend's chest is marked as illegal to _search_, then _all_ items in the quickloot interface are marked as illegal to take, even if only one of them actually is.

To prove this, [I have compiled an Imgur album showcasing this bug, with descriptions on each image](https://imgur.com/a/FNbKmoz).

I hope this helps clear things up.

**Comment by Ryan-rsm-McKenzie** [comment]
I've investigated this bug further, and I can conclude that QuickLoot matches vanilla behavior. It's mostly an issue with vanilla UI bugs. Basically, there are 2 different cases:

* The container is marked as "Steal from", but an item inside is not marked as stolen:
  * Taking that item through the vanilla item menu _will_ trigger the steal alarm and marks the item as stolen in your inventory. QuickLoot matches vanilla behavior here.
* The container is marked as "Search", but an item inside is marked as stolen:
  * Taking that item through the vanilla item menu will _not_ trigger the steal alarm and does _not_ mark the item as stolen in your inventory. QuickLoot matches vanilla behavior here.
