### ISSUE TITLE
Customizing keybindings option

### ISSUE THREAD

**Issue by flightifyy** [Ryan-rsm-McKenzie/QuickLootRE#115]
I want to change the keybinds to open a container and to quickly take out an item.
So basically want to open an container with E and to loot with the quick loot menu with R (switching the keybinds).

Thanks so much for the rewrite.

**Comment by Ryan-rsm-McKenzie** [comment]
This will never happen

**Comment by flightifyy** [comment]
Where in the code can I change the keybinds myself?

**Comment by flightifyy** [comment]
> This will never happen

Where in the code can I change the keybinds myself?
