### ISSUE TITLE
Game-start UI Stacking Bug

### ISSUE THREAD

**Issue by Velgus** [Ryan-rsm-McKenzie/QuickLootRE#12]
**Issue:** When loading up a save game, if the _first time_ the QuickLoot menu is opened is to pickpocket from an NPC, then the "Theft" and "Item Type" icons will be stacked on top of each other. This does not happen subsequently (ie. if you leave the QuickLoot menu, then re-open it) while you remain in the game world.

**Reproduction:**
1. Launch Skyrim
2. Load a save game
3. Walk up to an NPC and target them (do not open QuickLoot menu via any other method prior)
4. Switch to Sneak mode

**Image:** https://i.imgur.com/W9uAZtt.jpg (Ignore the lack of "sneak" cursor, I use other HUD mods)

**Comment by Ryan-rsm-McKenzie** [comment]
I haven't observed this behavior in the latest builds, so I'll close this issue
