### ISSUE TITLE
QuickLoot menu disapears when exiting "search" menu

### ISSUE THREAD

**Issue by MattSturgeon** [Ryan-rsm-McKenzie/QuickLootRE#120]
I'm assuming this is unintended behavior and I couldn't find it reported already. I don't know how important this is to prioritize... Personally I find it a minor annoyance, though.

#### Steps to reproduce:

- When I look at a container the QuickLoot menu shows
- When I hit my "search" hotkey, the full container inventory menu opens (and QuickLoot menu is hidden)
- **When I exit the full container menu (by pressing `TAB`) the vanilla `Press E to search` prompt is shown, instead of the QuickLoot menu (bug?)**
- When I look away from the container the vanilla prompt disappears.
- When I again look back at the container the QuickLoot menu shows again.

#### Video

https://user-images.githubusercontent.com/5046562/147513598-d43dc4bf-57a3-4494-951f-b93b74beec27.mp4

**Comment by Ryan-rsm-McKenzie** [comment]
This is the intended behaviour.

**Comment by MattSturgeon** [comment]
Thanks for clarifying. If you ever add configurable settings, could you consider adding an option to have the quickloot menu re-appear upon exiting the full inventory menu?
