### ISSUE TITLE
No item icons are being displayed at all

### ISSUE THREAD

**Issue by MartinHaeusler** [Ryan-rsm-McKenzie/QuickLootRE#121]
This is a screenshot of my Skyrim AE, everything updated to latest version:

[![screenshot.jpg](https://i.postimg.cc/rw3L55Rt/screenshot.jpg)](https://postimg.cc/VJqT8rRY)

This is the way QuickLoot RE looks for me. While it is fully functional (thanks for that!), I don't get to see any item icons at all, regardless of which item it is. Also, the centered text makes it really hard to quickly skim throuhg item lists.

Did I do anything wrong during setup? Or is this the way it is supposed to look...?

**Comment by Ryan-rsm-McKenzie** [comment]
There are no icons
