### ISSUE TITLE
UI Suggestion - No "Take All" when Pickpocketing

### ISSUE THREAD

**Issue by Velgus** [Ryan-rsm-McKenzie/QuickLootRE#21]
~When you go to the vanilla pickpocket (EDIT: or loot) menu, invisibility breaks. This might be a bit too annoying with QuickLoot (given you could 'accidentally' open the QuickLoot pickpocket menu), but it would still make sense to have invisibility break after taking an item in the QuickLoot menu.~ EDIT: Fixed in 1.7.14 - re-named issue to correspond with the remaining suggestion.

That aside, there is no "Take All" option for the vanilla pickpocket UI, and it's also non-functional with QuickLoot's pickpocketing, so perhaps having the button prompt for it disappear in the QuickLoot pickpocket menu would also make sense.

~EDIT: The invisibility issue actually applies to 'all' forms of looting while invisible, not just pickpocketing.~

**Comment by SniffleMan** [comment]
Invisibility now breaks in 1.7.14

**Comment by Velgus** [comment]
Just confirming that invisibility breaking does work in 1.7.14.

**Comment by Ryan-rsm-McKenzie** [comment]
Added in 1.18.0
