### ISSUE TITLE
Suggestion: Steam Input Controller Support

### ISSUE THREAD

**Issue by Velgus** [Ryan-rsm-McKenzie/QuickLootRE#34]
I know you don't have a Steam controller or PS4 controller, but both those controllers (and also XBox One/360 controllers) can be used _through_ Steam Input. Any controller supporting either DirectInput or XInput can actually work through Steam Input.

This would add indirect controller support for anyone who is running the game off Steam. Since this includes almost everyone playing legally, this basically provides controller support for everyone using just about any possible controller type.

[Information on Steam Input (including Developer sections and API)](https://partner.steamgames.com/doc/features/steam_controller)

**Comment by Ryan-rsm-McKenzie** [comment]
Community comments seem to indicate that quickloot works with ps4 controllers, so i'll mark this as closed
