### ISSUE TITLE
Add reversible filters

### ISSUE THREAD

**Issue by Ryan-rsm-McKenzie** [Ryan-rsm-McKenzie/QuickLootRE#39]

**Comment by Velgus** [comment]
As a small request to add to this - could you also make a variant of the valuePerWeight filter that throws "0 weight" items at the top, instead of the bottom? I know that this is not how SkyUI does it for inventory sorting, but it makes more sense from a looting perspective.

**Comment by SniffleMan** [comment]
If you sort by descending, shouldn't the heaviest items come first?

**Comment by Velgus** [comment]
Yes, sorry, that was just a mistake.

What I meant though, is that the Ascending filter goes:
- Value/Weight ascending
- 0 Weight items at the bottom

That is the way that SkyUI does it by default as well, if you use its Value/Weight sorting in the inventory menu.

That said, for the purposes of looting, it would be better if that filter worked like:
- 0 Weight items at the top
- Value/Weight ascending for weight greater than 0

**Comment by SVG1** [comment]
Maybe make an adaptive sorting?
For example: the sorting itself adjusts to the player. Those items that a player often picks up through the quickloot move up the list. The truth probably will have to write an additional script on papyrus to preserve the player’s preferences in save file.

**Comment by SniffleMan** [comment]
I believe this is how it works in the latest version

**Comment by Velgus** [comment]
You are correct, SniffleMan - that is how it works in the latest version. Last time I checked was a while ago, and it didn't work like that back then. Thanks!

**Comment by Velgus** [comment]
Oh, I see - if you were referring to the "priority" sorting, it still doesn't quite align that way either. For example, it puts enchanted items at the top, but will still have heavy and low value/weight armors above certain things like alchemy ingredients.

**Comment by SVG1** [comment]
Once upon a time, in 2016 I set up for myself the sorting priority in quickloot 1.1f for Skyrim LE. I also wanted it here, but I can't compile it.  It's strange that those old sources that compiled without any problems are not compiling now. I do not know what's the matter. Here is an approximate sorting order for me:
	// set priority
	enum Priority
	{
		QuestItem,
		Key,
		Gold,
		SoulGem,
		Gem,
		Ore,
		Ingot,
                DefaultIngredient,
                Strips,
                Leather,
                Hide,
                Remains,
                Misc,
                Clutter,
		EnchantedWeapon,
		EnchantedArmor,
		Potion,
		Poison,
		Amulet,
		Ring,
		Weapon,
		Armor,
		Other,
		Food = Other
	};

**Comment by SniffleMan** [comment]
i use different names for the enum

**Comment by SVG1** [comment]
I known. This is copy / paste from old source (quickloot 1.1f)

**Comment by SVG1** [comment]
Can you transfer the sorting by priority to a file *.json with the ability to add and delete keywords items?
Then each user will be able to customize the sorting to his taste.

		enum Priority : UInt32
		{
			kPriority_Key,
			kPriority_Gold,
			kPriority_LockPick,
			kPriority_Ammo,
			kPriority_SoulGem,
			kPriority_Potion,
			kPriority_Poison,
			kPriority_EnchantedWeapon,
			kPriority_EnchantedArmor,
			kPriority_Gem,
			kPriority_Amulet,
			kPriority_Ring,
			kPriority_Weapon,
			kPriority_Armor,
			kPriority_Food,
			kPriority_Other = kPriority_Food,
		};

**Comment by Ryan-rsm-McKenzie** [comment]
Implementing a custom priority enum would have no impact on item's priorities, since the enum is bound to actual code. Since reversible filters have been added, I'm closing this.
