### ISSUE TITLE
Toggle Mod Feature

### ISSUE THREAD

**Issue by Velgus** [Ryan-rsm-McKenzie/QuickLootRE#42]
Just a request for a feature return from the version of the mod for Classic, and the previous SSE port.

In the older versions, you could toggle the full functionality of the mod on and off in-game by holding down the equip/unequip key for 2 seconds.

**Comment by SniffleMan** [comment]
Added in 1.15.0

**Comment by Velgus** [comment]
Holding ESC as mentioned in the Readme doesn't seem to work for toggling it. Could it possibly be conflicting with Stay At The System Page - Updated?

**Comment by SniffleMan** [comment]
Should be fixed in 1.15.2

**Comment by Velgus** [comment]
Sorry for the delay.

As of the latest version (1.15.3), it will 'show' as toggling via the notifications in the top-left, but it seems to have an issue with toggling back 'on'. It will disable when holding ESC for 2 seconds, but won't re-enable when holding it for 2 seconds again (the notification will show, but it won't actually work).

**Comment by Ryan-rsm-McKenzie** [comment]
You must refresh your crosshair target when you toggle the lootmenu on in order to open it
