### ISSUE TITLE
Suggestion: Implement Signature Scanner

### ISSUE THREAD

**Issue by Velgus** [Ryan-rsm-McKenzie/QuickLootRE#46]
I'm putting this here, but I think it applies to all your mods. NasGorTelorCeplok created a signature scanner class that will work for SKSE DLL mods - this should make it so as you don't have to worry about updating the memory offsets between SSE version updates. The source is open and may be used for other mods.

Here's a link to one of his mod pages, where the code is available: https://www.nexusmods.com/skyrimspecialedition/mods/21527?tab=files

**Comment by Ryan-rsm-McKenzie** [comment]
Quickloot uses offsets that can't be pattern scanned for, or are provided by SKSE. I don't intend to change this functionality.
