### ISSUE TITLE
Allow ability use while menu is open

### ISSUE THREAD

**Issue by King-Troller** [Ryan-rsm-McKenzie/QuickLootRE#49]
If it's possible it would be nice to be able to use abilities/shouts while the menu is open. I use a few different abilities like the vampires raise dead ability that targets corpses, but if i'm close enough for the quickloot menu to open it intercepts my ability key and won't let me use it until I back away from the corpse.

**Comment by Ryan-rsm-McKenzie** [comment]
You can attack and shout while the menu is open, unless you bind them to quickloot keys
