### ISSUE TITLE
Menu doesn't close

### ISSUE THREAD

**Issue by Wargazm** [Ryan-rsm-McKenzie/QuickLootRE#50]
I don't know if I'm just not setting something up correctly, but the menu doesn't close when I look away from a container (in this case, a dead body that I am looting).  I look at the body, the quick loot menu opens....and then it just stays there, forever.  The only way I've found to disable it is to hold ESC for two seconds to disable the mod altogether. 

Am I missing a config switch somewhere?

**Comment by Ryan-rsm-McKenzie** [comment]
Install engine fixes

**Comment by Wargazm** [comment]
ugh.  I am ashamed at myself.  thanks.
