### ISSUE TITLE
disableHarvest option would be nice.

### ISSUE THREAD

**Issue by jarrard** [Ryan-rsm-McKenzie/QuickLootRE#51]
I have a bit of an annoying, often I want to open all or press v (if I remember) to see the contents and their value (since ql doesn't show item value). 

BUT if you do Namira's quest the option to view contents in normal looting screen is replaced with Harvest Body, so you are basically forced to harvest body before going into the vanilla loot menu.

Seems this could also be a problem for vampires or other quests that add feeding or harvesting. 

A solution would be Add a different key bind option for vanilla loot access of body in these situations?

**Comment by Ryan-rsm-McKenzie** [comment]
The search key is intended to open the vanilla context menu. You'd get this menu without quickloot installed, so I don't intend to bypass it.
