### ISSUE TITLE
Source code reuse request

### ISSUE THREAD

**Issue by SteveTownsend** [Ryan-rsm-McKenzie/QuickLootRE#54]
Sorry for the issue spam, cannot see how else to contact mod authors. 

I am working to update Auto Harvest SE https://www.nexusmods.com/skyrimspecialedition/mods/17622 to fix some things that I hit when I am using it. I've ported it (mostly) to use CommonLibSSE, so thanks for all of that immense project. 

I want to convert some of the currently-scripted logic to native C++. The logic for item looting in this mod seems to be part of what I need and I wanted to run that by the mod authors before going ahead. I'll cite the License in the new mod. Is this OK, please?

Thanks,
Steve Townsend
https://stackoverflow.com/users/210102/steve-townsend

**Comment by Ryan-rsm-McKenzie** [comment]
This is mod is released under an MIT license, so you can do whatever you want with the source code. However I'll warn you that when I wrote this, I understood very little about reverse engineering/c++/skyrim. So if there's something specific you're looking for, feel free to ask about it as I've probably learned better/safer ways to do it that's not reflected in this source code, especially if it's related to the inventory.

**Comment by SteveTownsend** [comment]
Thanks Ryan. I do have a couple of things that are problematic but I'll
experiment some more so I can forward focused questions to you on stuff
that is still unreliable. CommonLibSSE makes all this way easier though.

**Comment by SteveTownsend** [comment]
I have the AutoHarvest SE code running quite well over CommonLibSSE. A lot of what was in script is now native. There are a couple of things I could not make work. 
1. I cannot get events published from C++ to script. An example of old code with a comment showing how I am trying to plumb for CLSSE
`
	// TODO get this to compile
	// vm->SendEvent(m_aliasHandle, objectGlowEvent, RE::MakeFunctionArguments(m_refr, subEvent_glowObject));
	ObjectGlowEventFunctor argGlow(reinterpret_cast<TESObjectREFR*>(m_refr), ObjectGlowDuration);
	m_registry->QueueEvent(m_aliasHandle, &objectGlowEvent, &argGlow);
`
2. When I needed to introspect the VMAD for a REFR I had to handle that via a scripted event to cast to the object's script type. Is there any way to introspect the VMAD from native code?
e.g.
`
void SearchTask::TriggerGetCritterIngredient()
{
	CritterIngredientEventFunctor args(reinterpret_cast<TESObjectREFR*>(m_refr));
	m_registry->QueueEvent(m_aliasHandle, &critterIngredientEvent, &args);
}
`
resulting in async resolution of the critter to its ingredient, and then a call back to native to register that mapping:
`
Event OnGetCritterIngredient(ObjectReference akTarget)
	;DebugTrace("OnGetCritterIngredient " + akTarget.GetDisplayName() + "RefID(" +  akTarget.GetFormID() + ")  BaseID(" + akTarget.GetBaseObject().GetFormID() + ")" )
	form baseForm = akTarget.GetBaseObject()
    Critter thisCritter = akTarget as Critter
	if (thisCritter)
       	;DebugTrace("setting ingredient " + thisCritter.lootable.GetName() + " for critter " + baseForm.GetName())
       	SetIngredientForCritter(baseForm, thisCritter.lootable)
    endif
endEvent
`

**Comment by Ryan-rsm-McKenzie** [comment]
1) I need to know the types of all the variables you're using

2) Are you trying to dynamically determine if your script is attached to a given reference?

**Comment by SteveTownsend** [comment]
Thanks for replying Ryan. I'm stripping down my load order to test more thoroughly and will get back to you once I am clear to get what you requested on a stable setup.

**Comment by SteveTownsend** [comment]
I managed to get the code compiled though there was an ambiguity in the PackValue passthrough between bool and unsigned int, I had to comment out uint in Variable/h to get it to compile. IN any case my plugin now has no compile-time dependencies on SKSE, it's all CommonLibSSE. Thanks for the library, it's an awesome piece of work.
```
#if 0
			template <class T, typename std::enable_if_t<is_uint32_compat<T>::value, int> = 0>
			inline void SetData(T&& a_val)
			{
				SetUInt(std::forward<T>(a_val));
			}
#endif
```

**Comment by Ryan-rsm-McKenzie** [comment]
1) `SKSE::RegistrationSet` is meant to act as a wrapper for dispatching events to registered scripts, and has serialization capabilities.

2) Are you trying to invoke the activate event on a script? Or are you trying to run a custom event instead?

**Comment by SteveTownsend** [comment]
Thanks for the update. The code **seems** to be working OK if you cannot spare more time to look...

1. Hmm are you saying my StopObjectGlow is the wrong way to crack the nut of invoking a custom event in script? It's a straight conversion from SKSE to CLibSSE of the existing C++ -> Papyrus handoff in the existing mod, but I would not be surprised if you are right.  The PSC part looks like this - I believe the Quest alias `m_aliasHandle` used in the C++is a mod artifact to facilitate passing arbitrary event info about any REFR to the PSC. The mod filters and then handles **a lot** of REFRs to allow selective automatic looting and visual highlighting. Although my new version does a lot more of the work in C++ now, wherever I could grok and implement equivalent function.
```
Event OnObjectGlowStop(ObjectReference akTargetRef)
	;DebugTrace("------------ Event OnObjectGlowStop " + akTargetRef.GetDisplayName())
	EffectShader effShader = Game.GetFormFromFile(0x04000, "AutoHarvestSE.esp") as EffectShader
	if (effShader)
		effShader.Stop(akTargetRef)
	endif
endEvent
```

2. I am passing the REFR to script so I can selectively activate it. I am OK with pushing my updated codebase to Github if that would be easier than posting snippets here and there, but the event handler I am invoking here which introspects the ACTI to find out if it's minable is below.

Relevant snippet:
```
		MineOreScript oreScript = akTarget as MineOreScript
		if (oreScript)
			; brute force ore gathering to bypass tedious MineOreScript/Furniture handshaking
			int available = oreScript.ResourceCountCurrent
			if (available == -1)
       		    ;DebugTrace("Vein not yet initialized, start mining")
       		else
       		    ;DebugTrace("Vein has ore available: " + remaining)
       		endif
```

Full event handler:
```
Event OnAutoHarvest(ObjectReference akTarget, int itemType, int count, bool silent, bool ignoreBlock)
	;DebugTrace("OnAutoHarvest:Run: " + akTarget.GetDisplayName() + "RefID(" +  akTarget.GetFormID() + ")  BaseID(" + akTarget.GetBaseObject().GetFormID() + ")" ) 
	;DebugTrace("item type: " + itemType + ", type-mine: " + objType_mine + ", do not notify: " + silent + ", ignore activation blocking: " + ignoreBlock) 
	
	Actor akActivator = Game.GetPlayer()

	if (IsBookObject(itemType))
		akActivator.AddItem(akTarget, count, true)
	elseif (itemType == objType_Soulgem && akTarget.GetLinkedRef(None))
		; no-op but must still unlock

	elseif (itemType == objType_Mine)
		;DebugTrace("Harvesting Ore")
		MineOreScript oreScript = akTarget as MineOreScript
		if (oreScript)
			; brute force ore gathering to bypass tedious MineOreScript/Furniture handshaking
			int available = oreScript.ResourceCountCurrent
			if (available == -1)
       		    ;DebugTrace("Vein not yet initialized, start mining")
       		else
       		    ;DebugTrace("Vein has ore available: " + remaining)
       		endif

			int remaining = available
			; 'remaining' is set to -1 before the vein is initialized
			while (remaining != 0 && available - remaining < count)
   				;DebugTrace("Trigger harvesting")
				oreScript.giveOre()
				remaining = oreScript.ResourceCountCurrent
				;DebugTrace("Ore harvested, amount remaining: " + remaining)
			endwhile
			;DebugTrace("Done harvesting, retrieved " + available - remaining)
		endif
		; don't try to re-harvest excluded, depleted or malformed vein again until we revisit the cell
		BlockReference(akTarget)

    ; Blocked activators may be looted according to a config setting
	elseif (!akTarget.IsActivationBlocked() || ignoreBlock)
    	form baseForm = akTarget.GetBaseObject()
		if (akTarget.IsActivationBlocked())
			;DebugTrace("Activator blocked " + akTarget.GetDisplayName())
		endif
		if (itemType == objType_Flora)
			if (ActivateEx(akTarget, akActivator, silent) && (greenThumbPerk && akActivator.HasPerk(greenThumbPerk)) as bool)
				float greenThumbValue = greenThumbPerk.GetNthEntryValue(0, 0)
				int countPP = ((count * greenThumbValue) - count) as int
				if (countPP >= 1)
					akActivator.AddItem(baseForm, countPP, true)
				endif
			endif
		elseif (itemType == objType_Critter)
			ActivateEx(akTarget, akActivator, silent)
		elseif (itemType == objType_Septim && baseForm.GetType() == getType_kFlora)
			ActivateEx(akTarget, akActivator, silent)
		else
			if (ActivateEx(akTarget, akActivator, false) && !silent)
				string activateMsg = none
				if (count >= 2)
					string translation = GetTranslation("$AHSE_ACTIVATE(COUNT)_MSG")
					
					string[] targets = New String[2]
					targets[0] = "{ITEMNAME}"
					targets[1] = "{COUNT}"

					string[] replacements = New String[2]
					replacements[0] = baseForm.GetName()
					replacements[1] = count as string
					
					activateMsg = ReplaceArray(translation, targets, replacements)
				else
					string translation = GetTranslation("$AHSE_ACTIVATE_MSG")
					activateMsg = Replace(translation, "{ITEMNAME}", baseForm.GetName())
				endif
				if (activateMsg)
					Debug.Notification(activateMsg)
				endif
			endif
		endif

		;DebugTrace("OnAutoHarvest:Activated:" + akTarget.GetDisplayName() + "RefID(" +  akTarget.GetFormID() + ")  BaseID(" + akTarget.GetBaseObject().GetFormID() + ")" )
	endif
	
	UnlockAutoHarvest(akTarget)
endEvent
```

**Comment by Ryan-rsm-McKenzie** [comment]
`SKSE::RegistrationSet` acts as a wrapper for dispatching events to scripts, so you don't have to prepare the arguments yourself and make raw calls to the vm. In your example we could do:
```
SKSE::RegistrationSet<const RE::TESObjectREFR*> onAutoHarvest("OnAutoHarvest");
```
Then we just need to register the script:
```
void RegisterOnAutoHarvest(RE::StaticFunctionTag*, const RE::TESForm* a_myScript)
{
	onAutoHarvest.Register(a_myScript);
}
```
Then we can dispatch events to it:
```
void MyFunc(const RE::TESObjectREFR* a_myRef)
{
	onAutoHarvest.QueueEvent(a_myRef);
}
```

**Comment by SteveTownsend** [comment]
OK, I think I see how this works, Again, a simplification of the current code. Thanks for the info, I'll give this a try today.

**Comment by SteveTownsend** [comment]
This is working but I had to update RegistrtionSet to support the structure of my ESP, which I gaterh (thanks Google) is pretty common - it links a Quest to a RefAlias forced to the player, which means I have to be able to Register RE::BGSRefAlias* as well as RE::TESForm*. Code below, could be done via a template method but you get the idea:
```
			bool Register(const RE::BGSRefAlias* a_refAlias);
			bool Unregister(const RE::BGSRefAlias* a_refAlias);
```
```
		// Pseudo FormType ID for ReferenceAlias to support quests linked to Player - out-of-range FormType IDs from SKSE/GameForms.h->FormType
		// are not defined in CommonLibSSE
		constexpr RE::VMTypeID RefAliasID = static_cast<RE::VMTypeID>(RE::FormType::Max) + 2;

		bool RegistrationSetBase::Register(const RE::BGSRefAlias* a_refAlias)
		{
			assert(a_refAlias);
			auto vm = RE::BSScript::Internal::VirtualMachine::GetSingleton();
			auto policy = vm ? vm->GetObjectHandlePolicy() : nullptr;
			if (!policy) {
				_ERROR("Failed to get RefAlias handle policy!");
				return false;
			}

			const auto invalidHandle = policy->EmptyHandle();
			const auto handle = policy->GetHandleForObject(RefAliasID, a_refAlias);
			if (handle == invalidHandle) {
				_ERROR("Failed to create RefAlias handle!");
				return false;
			}

			_lock.lock();
			auto result = _handles.insert(handle);
			_lock.unlock();

			if (!result.second) {
				_WARNING("RefAlias Handle already registered (%u)", handle);
			}
			else {
				policy->PersistHandle(handle);
			}
			return result.second;
		}


		bool RegistrationSetBase::Unregister(const RE::BGSRefAlias* a_refAlias)
		{
			assert(a_refAlias);
			auto vm = RE::BSScript::Internal::VirtualMachine::GetSingleton();
			auto policy = vm ? vm->GetObjectHandlePolicy() : nullptr;
			if (!policy) {
				_ERROR("Failed to get handle policy!");
				return false;
			}

			auto invalidHandle = policy->EmptyHandle();
			const auto handle = policy->GetHandleForObject(RefAliasID, a_refAlias);
			if (handle == invalidHandle) {
				_ERROR("Failed to create handle!");
				return false;
			}

			Locker locker(_lock);
			auto it = _handles.find(handle);
			if (it == _handles.end()) {
				_WARNING("Could not find registration");
				return false;
			}
			else {
				policy->ReleaseHandle(*it);
				_handles.erase(it);
				return true;
			}
		}
```

**Comment by Ryan-rsm-McKenzie** [comment]
`SKSE::RegistrationSet` (and much of the papyrus wrappers) don't support reference aliases because I've never written anything that uses them. However, I can add support for them if you need.

**Comment by SteveTownsend** [comment]
Well, this is literally all I need them for. But "Quest linked to Player via RefAlias" seems like a moderately common way to propagate events to scripts, so at least this much would likely be of broader utility. I'm happy to keep this in a fork if it's too much work for you. I'm 100% rid of SKSE includes at this point, which is great.

**Comment by SteveTownsend** [comment]
I published the revised Auto Harvest 2 SE code to Github at https://github.com/SteveTownsend/AutoHarvestSE. I need to write some documentation but will plan to upload the mod to the existing Nexus location as a beta in the next few days. I already got permission from towawot to do this. Maybe I can get some playtesters on Discord first but I've spent many hours working through the nasty edge cases so I am cautiously optimistic it's stable.
I am still reliant on private mods for ReferenceAlias but that's fine with me. I made some rough and ready logging updates to add milliseconds and a thread id in case you are interested.
Thanks again for all your help. idk how you found time to build out this library, it's a serious piece of software.

**Comment by Ryan-rsm-McKenzie** [comment]
I've finally added alias support for the vm wrappers
I can take a look at the extensions for the logger as well

**Comment by SteveTownsend** [comment]
That's generous of you, thanks. I sync-ed up yesterday but will do so again today to pick up the RefAlias mods and retest. I'll get a code patch file for you to review on the logging. Thread id is clean, timestamp with milliseconds not so great imo. I'll see if I can improve it before sending to you.

**Comment by SteveTownsend** [comment]
Had to comment out a line in NiKeyBasedInterpolator.h to get it building:

```
//#include "NiAnimationKey.h"
#include "RE/NetImmerse/NiRefObject/NiObject/NiInterpolator/NiInterpolator.h"
```

**Comment by SteveTownsend** [comment]
My logging patch for milliseconds time and thread-id is at https://drive.google.com/open?id=1_4Gta1SAFZU6D2zbbaUmfQkyVmgNYJDq
