### ISSUE TITLE
Quickloot menu doesn't open when trying to pickpocket someone.

### ISSUE THREAD

**Issue by TwistedModding** [Ryan-rsm-McKenzie/QuickLootRE#58]
Exactly as title says.

Trying to sneak to pickpocket someone won't bring up the quickloot menu meaning you have to pickpocket as you normally would by going into there inventory.

**Comment by Ryan-rsm-McKenzie** [comment]
This is probably a feature I won't port

**Comment by NielsGx** [comment]
Well at least it's easier to pickpocket someone without this feature

**Comment by zhuabaobao123** [comment]
Come on, I love you God

**Comment by Naarin** [comment]
Will there be a pickpocket / lockpick auto show update ? it feels it would be so much perfect with it.

**Comment by Ryan-rsm-McKenzie** [comment]
I have no plans of implementing this
