### ISSUE TITLE
Mouse key icon does not display properly

### ISSUE THREAD

**Issue by MadCat221** [Ryan-rsm-McKenzie/QuickLootRE#59]
I use a Logitech MX518 and use the Mouse 4 key as the use/activate key. Instead of the usual "M4" interface key icon, it displays 2/@ on the quick loot menu. Screenshots as follows:

Quickloot menu:
https://i.imgur.com/e6B6erG.jpg

After using the regular loot menu option and closing the container:
https://i.imgur.com/FL6pU35.jpg

**Comment by Ryan-rsm-McKenzie** [comment]
Should be fixed in 2.0.2
