### ISSUE TITLE
Regular loot menu open when trying to loot with gamepad

### ISSUE THREAD

**Issue by patrickclark9** [Ryan-rsm-McKenzie/QuickLootRE#60]
The regular loot menu still opens when trying to loot through the quick loot menu with gamepad, it works fine when using keyboard and mouse.Could it be incompatibility with some gamepad mods (like gamepad++)?

**Comment by Ryan-rsm-McKenzie** [comment]
Highly likely an incompatibility with Gamepad++, try looting without it

**Comment by patrickclark9** [comment]
it works without it, just tested.Sorry for the inconvenience, I'll try and figure out if it's possible to run the 2 mods together

**Comment by Ryan-rsm-McKenzie** [comment]
Does it still display the correct button?

**Comment by patrickclark9** [comment]
yes the button is correct, looting works too actually, just as soon as you loot through the quick loot menu, it immediately opens the regular container loot menu.

**Comment by Ryan-rsm-McKenzie** [comment]
See if 2.0.2.1 helps

**Comment by patrickclark9** [comment]
I've tested the new version but it still opens the original loot menu. As an update, the game CTDs after trying to loot a couple containers.

**Comment by Ryan-rsm-McKenzie** [comment]
fixed in 2.1.1
