### ISSUE TITLE
QuickLoot menu should auto-dismiss when engaged in dialogue

### ISSUE THREAD

**Issue by Deigue** [Ryan-rsm-McKenzie/QuickLootRE#65]
Was killing a couple wolves in the forest, and naturally the QuickLoot menu shows up as expected.
Immediately an NPC interrupts me (the one that gives you something and take care of it, and he will come back for it later)
In this particular instance, when the 2 dialogue options are presented and while he is talking to you, the QuickLoot menu is still left up, kind of clashing with the 2 dialogue options available.

**Comment by Ryan-rsm-McKenzie** [comment]
fixed in 2.3.1
