### ISSUE TITLE
Quest Update when Looting Container

### ISSUE THREAD

**Issue by IanMunster** [Ryan-rsm-McKenzie/QuickLootRE#69]
Quests that require you to loot a container do not update when looted with QuickLoot.

Tested in Intro Sequence "(Optional) Look in the Barrel for Potions."

I don't think this was a problem with v1.
Manually opening the Container updates the Quest Stage.

**Comment by Ryan-rsm-McKenzie** [comment]
v1 had this same issue. This fix is to manually dispatch events to the scripts attached to the containers, but the game will bug out if the scripts do weird shit in the event blocks. See [Elysium Estate](https://www.nexusmods.com/skyrimspecialedition/mods/4119) for an example, which has containers that activate themselves inside the activate event block.

**Comment by IanMunster** [comment]
Is an idea to not show the QuickLoot menu on containers with scripts?
So the player wont accidentally loot the container without a quest update?

And do the vanilla containers scripts do this kind of weird shit or is it only mod added?

**Comment by Ryan-rsm-McKenzie** [comment]
Only mod added containers do this.

**Comment by IanMunster** [comment]
Bug happens in "Unbound"
On both "Gunjar" ID: B1694 and "Potions Barrel"

**Comment by jbostrus** [comment]
> Is an idea to not show the QuickLoot menu on containers with scripts?
> So the player wont accidentally loot the container without a quest update?

This wouldn't work if the container has no scripts, but was in a quest alias which does have scripts. I guess you could do a lengthy chest of everything that referenced a container to see if there were scripts involved, but that may ultimately just confuse a player when "sometimes it works and sometimes it doesn't."

**Comment by Arthmoor** [comment]
It seems to me that it wouldn't be overly difficult to just have the mod send the OnActivate() event to any container that's being looked at since it's already mimicking the access to the inventory inside. The game fully expects that to be sent to the container when the player hits the button.

Not doing this appears to be breaking some vanilla quests because those events are not being sent.

**Comment by Alphyn-gunner** [comment]
I clearly remember this feature in the old Quick Loot. It just didn't show on quest-related containers.

**Comment by Ryan-rsm-McKenzie** [comment]
The old quickloot showed it on all containers if enabled

**Comment by Alphyn-gunner** [comment]
Hmm, I must be confusing it with some other loot-related mod then.

**Comment by IanMunster** [comment]
Wanted to report that the quest "[Blood's Honor](https://elderscrolls.fandom.com/wiki/Blood%27s_Honor)" (Companions) works perfectly fine with Quick Loot.
Looted the heads with Quick Loot and the quest got an update.

So so far it has only been "Unbound" that has an issue.

**Comment by IanMunster** [comment]
Sorry, wrong button, my mistake!
