### ISSUE TITLE
Quick Loot stopped working and doesn't shows itself

### ISSUE THREAD

**Issue by AxelJaeger-XIII** [Ryan-rsm-McKenzie/QuickLootRE#77]
Since version 2.4.2, Quick Loot simply stopped working and it doesn't appear when mousing over the containers, neither the vanilla interaction prompt appears but I can still open the containers...freezing the entire UI (I can only move the mouse cursor but the entire UI became unresponsive to any mouse or keyboard input).

The issue persist in version 2.4.3, in version 2.4.1 Quick Loot works but the interface keeps freezing when opening a container.

Version 2.4.0 seems to work without issues.

**Comment by IanMunster** [comment]
@AxelJaeger-XIII  When your UI freezes try hitting "Take All", this will close your UI so you can continue.
This works for me when the UI freezes.

**Comment by fenrir0054** [comment]
I have these same issues, both not displaying the Quick Loot part, as well as the frozen UI upon opening the loot UI. It happens in both version 2.4.3 and 2.4.2, however doesn't seem to have any issues with 2.4.1

This is the list of addons currently being used, but I haven't tested without them:

*Skyrim Project Optimization - Full Version.esm
*AHZmoreHUD.esl
*AHZmoreHUDInventory.esl
*FISS.esp
*SkyUI_SE.esp
*Realm of Lorkhan - Custom Alternate Start - Choose your own adventure.esp
*RaceMenu.esp
*RaceMenuPlugin.esp
*SovngardeFont.esp
*Experience.esp
*Extended UI.esp
*DearDiary.esp
*AMatterOfTime.esp
*SkyHUD.esp
*Oblivionesque Active Effects Icons For SkyUI.esp
*PaperHUD.esp

And the following SKSE plugins that don't have any .esp plugins:

Address Library for SKSE Plugins
PrivateProfileRedirector
StayAtSystemPageSE

**Comment by IanMunster** [comment]
We have the following overlapping mods:
- Sky UI SE
- Sky HUD
- Address Library for SKSE Plugins.

But I think, based on the issue starting to appear from version 2.4.2 and onward, it's a issue within Quickloot itself.
