### ISSUE TITLE
Non-interactable arrows showing pickup text

### ISSUE THREAD

**Issue by caligineux** [Ryan-rsm-McKenzie/QuickLootRE#86]
Archery companions will swap to using a default iron arrow when they run out of normal ammunition in their inventory. These default iron arrows should be non-interactable and not display anything when moused over. When running QuickLootRE, these arrows show a text to pick them up. Trying to pick up these arrows changes their text to the red "steal" notification which is also incorrect.

**Comment by Ryan-rsm-McKenzie** [comment]
This is vanilla behaviour
