### ISSUE TITLE
Will it safe to run if I install this beta version after I uninstall the unofficial update for QuickLoot RE?

### ISSUE THREAD

**Issue by cascadahk** [Ryan-rsm-McKenzie/QuickLootRE#89]
My English is suck so I make it short. : )

I have installed the unofficial update for QuickLoot RE for a period and now I want to try this beta version.

Will it crash my old save? If yes, how to solve it without starting a new save? Is that possible?

**Comment by dann1** [comment]
I did it without issues so far

**Comment by Ryan-rsm-McKenzie** [comment]
It's safe to install mid game
