### ISSUE TITLE
QuickLoot Menu Doesn't Disappear

### ISSUE THREAD

**Issue by Halliphax** [Ryan-rsm-McKenzie/QuickLootRE#90]
Using QuickLoot 2.7.1 on a vanilla Skyrim (1.5.80) game (and save game) with Address Libraries, SSE Engine Fixes, SkyUI, SKSE and C++ Redistributables 2015 - 2019 (x64 and x86) 14.27.29016.0

The QuickLoot menu will show for containers, however it will persist when navigating away from the container and continue to show on screen until the UI/HUD is updated with another element (activation prompt i.e to talk to an NPC or sleep in a bed).

**Comment by Ryan-rsm-McKenzie** [comment]
This is a bug with SKSE for that version of Skyrim

**Comment by Halliphax** [comment]
> 
> 
> This is a bug with SKSE for that version of Skyrim

So it is, just updated and all working. Cheers Ryan!
