### ISSUE TITLE
Hovering over a container while commanding a follower ends command mode

### ISSUE THREAD

**Issue by TheShiningAbsol** [Ryan-rsm-McKenzie/QuickLootRE#98]
When in follower command mode, hovering over any container - regardless of distance - will instantly drop you out of command mode, with the follower saying something like "anything else?". Can make it difficult to give commands in areas that have a lot of containers.

**Comment by TheDanielKemp** [comment]
Oh, so THAT'S why this was happening to me! This has been really annoying me too! I'd love to see a fix!
